### PR TITLE
Build Travis matrix with compatible Ruby/Rails versions

### PR DESCRIPTION
**Pull request by garettarrowood**

### CODE REVIEW

**Comment by garettarrowood** [comment]
@Tonkpils @ileitch -

These CI updates are being made to provide confidence in future changes necessary for a Rails 5.2+ compatibility upgrade. Do either of you have any reservations, or a preference about stopping support for earlier versions of Rails? `3.2`, `4.0` and `4.2` all seem like reasonable places to draw a line in the sand. Perhaps we could also not track Ruby versions below 2.3?

I know you two are not involved in this project much anymore. I will discuss this with my colleagues and just make a judgement call in the next 24 hours if I don't hear back.

**Comment by benlangfeld** [comment]
I suggest not providing support for any version of Ruby or Rails which no longer receives any kind of support from those upstream teams. This would currently mean [Rails 4.2+](https://guides.rubyonrails.org/maintenance_policy.html#severe-security-issues) and [Ruby 2.3+](https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/).

**Comment by benlangfeld** [comment]
https://github.com/ileitch/modis/pull/19 incorporates these changes as well as my suggestion for support above.

**Comment by garettarrowood** [comment]
Closing in preference of #19

**Pull request closed without merging**
